apiVersion: v2
name: kps
version: 0.0.0
dependencies:
  - name: kube-prometheus-stack
    version: 74.2.1
    repository: https://prometheus-community.github.io/helm-charts
  - name: prometheus-blackbox-exporter
    version: 10.1.0
    repository: https://prometheus-community.github.io/helm-charts
