apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: selectel-dns-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: selectel-dns-credentials
  data:
    - secretKey: username
      remoteRef:
        key: secret/cert-manager
        property: selectel-username
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: password
      remoteRef:
        key: secret/cert-manager
        property: selectel-password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: account_id
      remoteRef:
        key: secret/cert-manager
        property: selectel-account-id
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: project_id
      remoteRef:
        key: secret/cert-manager
        property: selectel-project-id
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
