sonarr:
  image:
    repository: ghcr.io/onedr0p/sonarr-develop
    tag: 4.0.14.2938
  env:
    TZ: Europe/Moscow
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        kubernetes.io/tls-acme: "true"
      hosts:
        - host: &host sonarr.home.devmem.ru
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host
  podSecurityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    fsGroupChangePolicy: OnRootMismatch
  persistence:
    config:
      enabled: true
      existingClaim: sonarr-config
    nfs-downloads:
      enabled: true
      existingClaim: nfs-downloads-pvc
      mountPath: /downloads
  resources:
    requests:
      cpu: 50m
      memory: 768Mi
    limits:
      cpu: 1000m
      memory: 1024Mi
