ingress-nginx:
  revisionHistoryLimit: 3
  controller:
    replicaCount: 2
    allowSnippetAnnotations: "true"
    service:
      loadBalancerIP: 192.168.13.240
      externalTrafficPolicy: Local
    extraArgs:
      default-ssl-certificate: cert-manager/devmem-ru-wildcard-tls
      enable-ssl-passthrough: "true"
      time-buckets: "0.005,0.01,0.025,0.05,0.1,0.25,0.5,1,2.5,5,10,30,60"
    config:
      # custom-http-errors: 401,403,404,500,501,502,503
      log-format-upstream: '{"msec":"$msec","connection":"$connection","connection_requests":"$connection_requests","pid":"$pid","request_id":"$request_id","status":"$status","remote_addr":"$remote_addr","remote_port":"$remote_port","remote_user":"$remote_user","request_length":"$request_length","request_method":"$request_method","request":"$request","request_uri":"$request_uri","args":"$args","bytes_sent":"$bytes_sent","body_bytes_sent":"$body_bytes_sent","http_referer":"$http_referer","http_user_agent":"$http_user_agent","http_host":"$http_host","server_name":"$server_name","server_protocol":"$server_protocol","scheme":"$scheme","request_time":"$request_time","upstream_connect_time":"$upstream_connect_time","upstream_header_time":"$upstream_header_time","upstream_response_time":"$upstream_response_time","upstream_response_length":"$upstream_response_length","upstream":"$upstream_addr","upstream_cache_status":"$upstream_cache_status","ssl_protocol":"$ssl_protocol","ssl_cipher":"$ssl_cipher","pipe":"$pipe","http_x_forwarded_for":"$http_x_forwarded_for","time_local":"$time_local","time_iso8601":"$time_iso8601"}'
      use-forwarded-headers: "true"
      enable-real-ip: "true"
      forwarded-for-header: proxy_protocol
      proxy-body-size: 2G
      client-body-buffer-size: 128m
      proxy-buffer-size: 16k
      proxy-busy-buffers-size: 16k
      annotations-risk-level: Critical
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                    - ingress-nginx
                - key: app.kubernetes.io/instance
                  operator: In
                  values:
                    - ingress-nginx
                - key: app.kubernetes.io/component
                  operator: In
                  values:
                    - controller
            topologyKey: kubernetes.io/hostname
  # defaultBackend:
  #   enabled: true
  #   image:
  #     repository: ghcr.io/tarampampam/error-pages
  #     tag: 2.16.0
  #   extraEnvs:
  #     - name: TEMPLATE_NAME
  #       value: connection
  #     - name: SHOW_DETAILS
  #       value: "false"
  #   livenessProbe:
  #     periodSeconds: 60
  #   readinessProbe:
  #     periodSeconds: 60
  tcp:
    58846: apps/deluge:58846
