portainer:
  image:
    repository: portainer/portainer-ce
    tag: 2.26.0
  service:
    type: ClusterIP
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      kubernetes.io/tls-acme: "true"
    hosts:
      - host: &host portainer.home.devmem.ru
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - *host
  persistence:
    enabled: true
    storageClass: longhorn
    size: 1Gi
  resources:
    requests:
      cpu: 10m
      memory: 128Mi
    limits:
      cpu: 1000m
      memory: 512Mi
