apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nextcloud
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: nextcloud
  data:
    - secretKey: admin-user
      remoteRef:
        key: secret/nextcloud
        property: admin-user
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: admin-password
      remoteRef:
        key: secret/nextcloud
        property: admin-password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: serverinfo-token
      remoteRef:
        key: secret/nextcloud
        property: serverinfo-token
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: postgresql-password
      remoteRef:
        key: secret/nextcloud
        property: postgresql-password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: postgresql-postgres-password
      remoteRef:
        key: secret/nextcloud
        property: postgresql-postgres-password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: smtp-host
      remoteRef:
        key: secret/common/smtp
        property: host
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: smtp-port
      remoteRef:
        key: secret/common/smtp
        property: port
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: smtp-username
      remoteRef:
        key: secret/common/smtp
        property: username
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: smtp-password
      remoteRef:
        key: secret/common/smtp
        property: password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
