---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: deluge-wireguard
  labels:
    app.kubernetes.io/name: deluge
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    template:
      data:
        wg0.conf: |
          [Interface]
          PrivateKey = {{ .wgPrivateKey }}
          Address = 10.44.0.4/32
          PostUp = '/root/wireguardup.sh'
          PostDown = '/root/wireguarddown.sh'

          [Peer]
          PublicKey = 10IYGaK04ISwjBPMfxcNMfZGMfmHl+Vd9eY3ePVV3hw=
          AllowedIPs = 0.0.0.0/0
          Endpoint = 192.168.10.99:51821
  data:
    - secretKey: wgPrivateKey
      remoteRef:
        key: secret/deluge
        property: wg-private-key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
