velero:
  initContainers:
    - name: velero-plugin-for-aws
      image: velero/velero-plugin-for-aws:v1.11.1
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: /target
          name: plugins
  configuration:
    extraEnvVars:
      TZ: "Europe/Moscow"
    backupStorageLocation:
      - name: backups-primary
        provider: aws
        bucket: velero
        config:
          region: main
          s3ForcePathStyle: true
          s3Url: https://s3.home.devmem.ru
          publicUrl: https://s3.devmem.ru
    volumeSnapshotLocation:
      - name: default
        provider: aws
        config:
          region: main
    features: EnableCSI
  credentials:
    useSecret: true
    existingSecret: velero
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 1000m
      memory: 512Mi
  upgradeJobResources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 1000m
      memory: 512Mi
