---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashy
  labels:
    app.kubernetes.io/name: dashy
  annotations:
    configmap.reloader.stakater.com/reload: "dashy-config"
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: dashy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dashy
    spec:
      containers:
        - name: dashy
          image: ghcr.io/lissy93/dashy:3.1.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          startupProbe:
            exec:
              command:
                - yarn
                - health-check
            failureThreshold: 3
            timeoutSeconds: 10
            periodSeconds: 90
            initialDelaySeconds: 40
          livenessProbe:
            exec:
              command:
                - yarn
                - health-check
            failureThreshold: 3
            timeoutSeconds: 10
            periodSeconds: 90
          readinessProbe:
            httpGet:
              port: 8080
            failureThreshold: 3
            timeoutSeconds: 10
            periodSeconds: 90
          volumeMounts:
            - mountPath: /app/user-data/conf.yml
              name: dashy-config
              subPath: conf.yml
          resources:
            requests:
              memory: 384Mi
              cpu: 20m
            limits:
              memory: 3072Mi
              cpu: 2000m
      volumes:
        - name: dashy-config
          configMap:
            name: dashy-config
---
apiVersion: v1
kind: Service
metadata:
  name: dashy
  labels:
    app.kubernetes.io/name: dashy
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: dashy
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dashy
  labels:
    app.kubernetes.io/name: dashy
  annotations:
    kubernetes.io/tls-acme: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: &host k8s.devmem.ru
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dashy
                port:
                  number: 8080
  tls:
    - hosts:
        - *host
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dashy-config
  labels:
    app.kubernetes.io/name: dashy
data:
  conf.yml: |
    ---
    appConfig:
      theme: material
      layout: vertical
      iconSize: small
      startingView: default
      defaultOpeningMethod: newtab
      statusCheck: false
      statusCheckInterval: 0
      faviconApi: allesedv
      routingMode: history
      enableMultiTasking: true
      widgetsAlwaysUseProxy: false
      webSearch:
        disableWebSearch: true
        searchEngine: duckduckgo
        openingMethod: newtab
        searchBangs: {}
      enableFontAwesome: true
      enableMaterialDesignIcons: true
      hideComponents:
        hideHeading: true
        hideNav: true
        hideSearch: true
        hideSettings: true
        hideFooter: true
      auth:
        enableGuestAccess: false
        users: []
        enableKeycloak: false
      showSplashScreen: false
      preventWriteToDisk: true
      preventLocalSave: false
      disableConfiguration: false
      allowConfigEdit: true
      enableServiceWorker: false
      disableContextMenu: false
      disableUpdateChecks: true
      disableSmartSort: false
      enableErrorReporting: false
      language: en
    pageInfo:
      title: homelab
      description: ''
      navLinks: []
      footerText: ''
    sections:
      - name: Infra
        displayData:
          sortBy: default
          rows: 1
          cols: 1
          collapsed: false
          hideForGuests: false
        items:
          - title: Proxmox
            icon: hl-proxmox
            url: https://proxmox.devmem.ru
            id: 0_496_proxmox
          - title: Portainer
            icon: hl-portainer
            url: https://portainer.home.devmem.ru
            id: 1_496_portainer
          - title: Minio
            icon: hl-minio
            url: https://minio.home.devmem.ru
            id: 2_496_minio
          - title: Gitea
            icon: hl-gitea
            url: https://git.devmem.ru
            id: 3_496_gitea
          - title: Jenkins
            icon: hl-jenkins
            url: https://jenkins.devmem.ru
            id: 4_496_jenkins
          - title: Nexus
            icon: https://nexus.home.devmem.ru/static/rapture/resources/favicon.ico
            url: https://nexus.home.devmem.ru
            id: 5_496_prometheus
          - title: LibreNMS
            icon: hl-librenms
            url: https://nms.home.devmem.ru
            id: 6_496_librenms
          - title: UniFi
            icon: hl-unifi
            url: https://unifi-ui.home.devmem.ru
            id: 7_496_unifi
          - title: FreeIPA
            icon: hl-freeipa
            url: https://ipa.home.devmem.ru
            id: 8_496_freeipa
          - title: phpLDAPadmin
            icon: hl-phpldapadmin
            url: https://ldap.home.devmem.ru
            id: 9_496_phpldapadmin
      - name: SPNAS
        displayData:
          sortBy: default
          rows: 1
          cols: 1
          collapsed: false
          hideForGuests: false
        items:
          - title: Plex
            icon: hl-plex
            url: https://plex.devmem.ru/web/index.html
            id: 0_389_plex
          - title: Tautulli
            icon: hl-tautulli
            url: https://tautulli.devmem.ru
            id: 1_389_tautulli
          - title: Ombi
            icon: hl-ombi
            url: https://ombi.devmem.ru
            id: 2_389_ombi
          - title: Jellyfin
            icon: hl-jellyfin
            url: https://j.devmem.ru/web/index.html
            id: 3_389_jellyfin
          - title: Deluge
            icon: hl-deluge
            url: https://deluge.home.devmem.ru
            id: 4_389_deluge
          - title: Sonarr
            icon: hl-sonarr
            url: https://sonarr.home.devmem.ru
            id: 5_389_sonarr
          - title: Radarr
            icon: hl-radarr
            url: https://radarr.home.devmem.ru
            id: 6_389_radarr
          - title: Prowlarr
            icon: hl-prowlarr
            url: https://prowlarr.home.devmem.ru
            id: 7_389_prowlarr
          - title: Jackett
            icon: hl-jackett
            url: https://jackett.home.devmem.ru
            id: 8_389_jackett
          - title: Lidarr
            icon: hl-lidarr
            url: https://lidarr.home.devmem.ru
            id: 9_389_lidarr
          - title: Bazarr
            icon: hl-bazarr
            url: https://bazarr.home.devmem.ru
            id: 10_389_bazarr
          - title: Huntarr
            icon: https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/huntarr.png
            url: https://huntarr.home.devmem.ru
            id: 11_389_huntarr
      - name: k8s
        displayData:
          sortBy: default
          rows: 1
          cols: 1
          collapsed: false
          hideForGuests: false
        items:
          - title: Argo CD
            icon: hl-argocd
            url: https://argocd.k8s.devmem.ru
            id: 0_278_argocd
          - title: Grafana
            icon: hl-grafana
            url: https://grafana.devmem.ru
            id: 1_278_grafana
          - title: Thanos
            icon: hl-thanos
            url: https://thanos.k8s.devmem.ru/alerts
            id: 2_278_thanos
          - title: Prometheus
            icon: hl-prometheus
            url: https://prometheus.k8s.devmem.ru/alerts
            id: 3_278_prometheus
          - title: Alertmanager
            icon: hl-alertmanager
            url: https://alertmanager.k8s.devmem.ru
            id: 4_278_alertmanager
          - title: Karma
            icon: mdi-recycle-variant
            url: https://karma.k8s.devmem.ru
            id: 5_278_karma
          - title: SigNoz
            icon: https://signoz.k8s.devmem.ru/signoz-signup.svg
            url: https://signoz.k8s.devmem.ru
            id: 6_278_signoz
          - title: Longhorn
            icon: hl-longhorn
            url: https://longhorn.k8s.devmem.ru
            id: 7_278_longhorn
          - title: Vault
            icon: hl-vault
            url: https://vault.k8s.devmem.ru
            id: 8_278_vault
          - title: Consul
            icon: https://consul.k8s.devmem.ru/ui/assets/favicon.ico
            url: https://consul.k8s.devmem.ru/
            id: 9_278_consul
          - title: Teleport
            icon: https://tele.devmem.ru/web/app/favicon.ico
            url: https://tele.devmem.ru
            id: 10_278_teleport
          - title: Goldilocks
            icon: https://goldilocks.k8s.devmem.ru/static/images/favicon.ico
            url: https://goldilocks.k8s.devmem.ru
            id: 12_278_goldilocks
      - name: Home
        displayData:
          sortBy: default
          rows: 1
          cols: 1
          collapsed: false
          hideForGuests: false
        items:
          - title: HomeAssistant
            icon: hl-home-assistant
            url: https://ha.devmem.ru
            id: 0_393_homeassistant
          - title: ESPHome
            icon: hl-esphome
            url: https://esphome.devmem.ru
            id: 1_393_esphome
          - title: Grocy
            icon: hl-grocy
            url: https://grocy.devmem.ru
            id: 2_393_grocy
          - title: ZHABridge
            icon: generative
            url: http://192.168.20.45/
            id: 3_393_zhabridge
      - name: Cloud
        displayData:
          sortBy: default
          rows: 1
          cols: 1
          collapsed: false
          hideForGuests: false
        items:
          - title: Nextcloud
            icon: hl-nextcloud
            url: https://cloud.devmem.ru
            id: 0_503_nextcloud
          - title: Syncthing
            icon: hl-syncthing
            url: https://syncthing.home.devmem.ru
            id: 3_503_syncthing
          - title: Vaultwarden
            icon: hl-bitwarden
            url: https://vaultwarden.devmem.ru
            id: 2_503_vaultwarden
      - name: HW
        displayData:
          sortBy: default
          rows: 1
          cols: 1
          collapsed: true
          hideForGuests: false
        items:
          - title: spsrv ipmi
            icon: generative
            url: https://spsrv-ipmi.home.devmem.ru
            id: 0_159_spsrvipmi
          - title: spmaxi ipmi
            icon: generative
            url: https://spmaxi-ipmi.home.devmem.ru
            id: 1_159_spmaxiipmi
          - title: ubnt-erx-krs
            icon: generative
            url: https://ubnt-erx-krs.home.devmem.ru
            id: 2_159_ubnterxkrs
          - title: ubnt-erx-cml
            icon: generative
            url: https://ubnt-erx-cml.home.devmem.ru
            id: 3_159_ubnterxcml
          - title: ubnt-esl24
            icon: generative
            url: https://ubnt-esl24.home.devmem.ru
            id: 4_159_ubntesl
          - title: DACHA 1
            icon: generative
            url: http://192.168.40.1/
            id: 5_159_dacha
          - title: DACHA 2
            icon: generative
            url: http://192.168.40.2/
            id: 6_159_dacha
