flaresolverr:
  image:
    repository: ghcr.io/flaresolverr/flaresolverr
    tag: v3.3.25
  env:
    TZ: Europe/Moscow
    LOG_LEVEL: info
    LOG_HTML: "false"
    CAPTCHA_SOLVER: none
  resources:
    requests:
      cpu: 10m
      memory: 128Mi
    limits:
      cpu: 2000m
      memory: 1024Mi
