syncthing:
  image:
    repository: syncthing/syncthing
    tag: 1.28.0
  env:
    TZ: Europe/Moscow
  service:
    listen:
      enabled: true
      type: LoadBalancer
      annotations:
        metallb.universe.tf/allow-shared-ip: syncthing
      loadBalancerIP: 192.168.13.244
      externalTrafficPolicy: Local
      ports:
        listen-tcp:
          enabled: true
          port: 22000
          protocol: TCP
          targetPort: 22000
    udp:
      enabled: true
      type: LoadBalancer
      annotations:
        metallb.universe.tf/allow-shared-ip: syncthing
      loadBalancerIP: 192.168.13.244
      externalTrafficPolicy: Local
      ports:
        discovery:
          enabled: true
          port: 21027
          protocol: UDP
          targetPort: 21027
        listen-udp:
          enabled: true
          port: 22000
          protocol: UDP
          targetPort: 22000
  ingress:
    main:
      enabled: true
      ingressClassName: nginx
      annotations:
        kubernetes.io/tls-acme: "true"
        nginx.ingress.kubernetes.io/whitelist-source-range: "10.244.0.0/16,192.168.0.0/16"
      hosts:
        - host: &host syncthing.home.devmem.ru
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host
  podSecurityContext:
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    fsGroupChangePolicy: OnRootMismatch
  persistence:
    data:
      enabled: true
      type: pvc
      accessMode: ReadWriteOnce
      storageClass: longhorn
      size: 1Gi
      mountPath: /var/syncthing
    nfs-downloads:
      enabled: true
      existingClaim: nfs-cloud-pvc
      mountPath: /cloud
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 1000m
      memory: 256Mi
  nodeSelector:
    devmem.ru/pve-host: spsrv
