signoz:
  clickhouse:
    user: admin
    password: <path:secret/data/signoz#clickhouse-password>
    persistence:
      enabled: true
      storageClass: longhorn
      accessModes:
        - ReadWriteOnce
      size: 20Gi
    coldStorage:
      enabled: true
      endpoint: https://s3.home.devmem.ru/signoz/data/
      accessKey: <path:secret/data/signoz#s3-key>
      secretAccess: <path:secret/data/signoz#s3-key-secret>
      defaultKeepFreeSpaceBytes: "1073741824"
    zookeeper:
      persistence:
        enabled: true
        storageClass: longhorn
        accessModes:
          - ReadWriteOnce
        size: 1Gi
  signoz:
    ingress:
      enabled: true
      className: nginx
      annotations:
        kubernetes.io/tls-acme: "true"
      hosts:
        - host: &host signoz.k8s.devmem.ru
          paths:
            - path: /
              pathType: Prefix
              port: 8080
      tls:
        - hosts:
            - *host
    persistence:
      enabled: true
      storageClass: longhorn
      accessModes:
        - ReadWriteOnce
      size: 1Gi
  otelCollector:
    service:
      annotations:
        metallb.universe.tf/loadBalancerIPs: 192.168.13.243
      type: LoadBalancer
    resources:
      limits:
        cpu: '2'
        memory: 1Gi
      requests:
        cpu: 200m
        memory: 512Mi
