vaultwarden:
  image:
    repository: vaultwarden/server
    tag: 1.32.4-alpine
  env:
    DATA_FOLDER: data
  envFrom:
    - secretRef:
        name: vaultwarden
  service:
    main:
      ports:
        websocket:
          enabled: false
  ingress:
    main:
      enabled: false
    simple:
      enabled: true
      ingressClassName: nginx
      annotations:
        nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
        kubernetes.io/tls-acme: "true"
      hosts:
        - host: &host vaultwarden.devmem.ru
          paths:
            - path: /
              pathType: Prefix
              service:
                port: 80
      tls:
        - hosts:
            - *host
  additionalContainers:
    - name: vaultwarden-ldap
      image: vividboarder/vaultwarden_ldap:1.0.1-alpine
      imagePullPolicy: Always
      volumeMounts:
        - name: config
          mountPath: /config.toml
          subPath: config.toml
      resources:
        requests:
          cpu: 10m
          memory: 32Mi
        limits:
          cpu: 100m
          memory: 64Mi
  persistence:
    data:
      enabled: true
      type: pvc
      accessMode: ReadWriteOnce
      storageClass: longhorn
      size: 1Gi
      mountPath: /data
    config:
      enabled: true
      type: secret
      name: vaultwarden-ldap
      mountPath: "-"
  postgresql:
    enabled: false
  mariadb:
    enabled: false
  resources:
    requests:
      cpu: 10m
      memory: 128Mi
    limits:
      cpu: 1000m
      memory: 256Mi
