apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: loki
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: loki
  data:
    - secretKey: LOKI_S3_KEY
      remoteRef:
        key: secret/loki
        property: s3-key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: LOKI_S3_SECRET
      remoteRef:
        key: secret/loki
        property: s3-key-secret
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
