apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitlab-runner
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    template:
      data:
        runner-registration-token: ""
        runner-token: {{ `"{{ .runnerToken }}"` }}
  data:
    - secretKey: runnerToken
      remoteRef:
        key: secret/gitlab-runner
        property: runner-token
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
